# Generated by Django manually due to sandbox limitations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_compra_custo_total_remove_compra_material_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alocacao_Obras_Equipes',
            new_name='Locacao_Obras_Equipes',
        ),
        migrations.RenameField(
            model_name='locacao_obras_equipes', # Use new model name here
            old_name='data_alocacao_inicio',
            new_name='data_locacao_inicio',
        ),
        migrations.RenameField(
            model_name='locacao_obras_equipes', # Use new model name here
            old_name='data_alocacao_fim',
            new_name='data_locacao_fim',
        ),
    ]
