# Generated by Django manually due to sandbox limitations

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_locacao_model_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='funcionario_locado',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='locacoes_individuais',
                to='core.funcionario'
            ),
        ),
    ]
