# Generated by Django 5.2.3 on 2025-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_locacao_obras_equipes_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='status_locacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status da Locação'),
        ),
    ]
