# Generated by Django 5.2.3 on 2025-06-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_locacao_obras_equipes_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_obras/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.obra')),
            ],
        ),
    ]
