# Generated by Django 5.0.4 on 2024-05-17 10:00
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_compra_created_at_compra_data_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usomaterial',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='usomaterial',
            name='obra',
        ),
        migrations.AddField(
            model_name='usomaterial',
            name='item_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='core.itemcompra'),
            preserve_default=False,
        ),
    ]
