# Generated by Django 5.2.3 on 2025-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_remover_campo_salario_funcionario"),
    ]

    operations = [
        migrations.AddField(
            model_name="obra",
            name="area_metragem",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Área em metros quadrados (m²)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
