# Generated by Django 5.2.3 on 2025-06-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('m²', 'Metro Quadrado'), ('kg', 'Quilograma'), ('saco', 'Saco')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_obra', models.CharField(max_length=255)),
                ('endereco_completo', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Planejada', 'Planejada'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_prevista_fim', models.DateField(blank=True, null=True)),
                ('data_real_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome_completo', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Admin'), ('gerente', 'Gerente')], max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=100, unique=True)),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_lideradas', to='core.funcionario')),
                ('membros', models.ManyToManyField(related_name='equipes_membro', to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Ferramentas', 'Ferramentas'), ('Outros', 'Outros')], max_length=50)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_extras', to='core.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_compra', models.DateField()),
                ('nota_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.material')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Alocacao_Obras_Equipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alocacao_inicio', models.DateField()),
                ('data_alocacao_fim', models.DateField(blank=True, null=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipe')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('Atraso', 'Atraso'), ('Falta Justificada', 'Falta Justificada'), ('Falta não Justificada', 'Falta não Justificada')], max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='core.funcionario')),
            ],
        ),
    ]
