# Generated by Django 5.2.3 on 2025-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_obra', models.CharField(max_length=255)),
                ('endereco_completo', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Planejada', 'Planejada'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=50)),
                ('data_inicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Admin'), ('gerente', 'Gerente')], max_length=50)),
            ],
        ),
    ]
