# Generated by Django 5.2.3 on 2025-06-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_obra_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao_obras_equipes',
            name='servico_externo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alocacao_obras_equipes',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.equipe'),
        ),
    ]
