# Generated by Django 5.2.3 on 2025-06-11 20:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alocacao_obras_equipes_servico_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='orcamento_previsto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='UsoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_uso', models.DateField(auto_now_add=True)),
                ('andar', models.CharField(choices=[('Terreo', 'Térreo'), ('1 Andar', '1º Andar'), ('2 Andar', '2º Andar'), ('Cobertura', 'Cobertura'), ('Area Externa', 'Área Externa'), ('Outro', 'Outro')], max_length=50)),
                ('categoria_uso', models.CharField(choices=[('Geral', 'Geral'), ('Eletrica', 'Elétrica'), ('Hidraulica', 'Hidráulica'), ('Alvenaria', 'Alvenaria'), ('Acabamento', 'Acabamento'), ('Estrutura', 'Estrutura'), ('Uso da Equipe', 'Uso da Equipe')], default='Geral', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='core.compra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_materiais', to='core.obra')),
            ],
        ),
    ]
