# Generated by Django 5.2.3 on 2025-06-11 22:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obra_orcamento_previsto_usomaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='custo_total',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='material',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='compra',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_total_liquido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_item', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.compra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_comprados', to='core.material')),
            ],
        ),
    ]
