# Generated by Django 5.2.3 on 2025-06-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_locacao_obras_equipes_status_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='valor_diaria_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_empreitada_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_metro_padrao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
