# Generated by Django 5.0.7 on 2025-06-15 12:00

from django.db import migrations

def populate_null_data_fim(apps, schema_editor):
    Locacao_Obras_Equipes = apps.get_model('core', 'Locacao_Obras_Equipes')
    # Iterate over records where data_locacao_fim is None
    for locacao in Locacao_Obras_Equipes.objects.filter(data_locacao_fim__isnull=True):
        if locacao.data_locacao_inicio:  # data_locacao_inicio should not be null
            locacao.data_locacao_fim = locacao.data_locacao_inicio
            locacao.save(update_fields=['data_locacao_fim']) # Efficiently save only the changed field

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_funcionario_valor_diaria_padrao_and_more'), # Depends on the previous migration
    ]

    operations = [
        migrations.RunPython(populate_null_data_fim),
    ]
