# Generated by Django manually for SGO project.
from decimal import Decimal
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fotoobra'), # Points to the actual previous migration
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='nivel_minimo_estoque',
            field=models.PositiveIntegerField(default=0, help_text='Nível mínimo de estoque para alerta. 0 para não alertar.'),
        ),
        migrations.AddField(
            model_name='material',
            name='quantidade_em_estoque',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
