# Generated by Django 5.2.3 on 2025-06-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_adicionar_metragem_obra"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcompra",
            name="categoria_uso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Geral", "Geral"),
                    ("Eletrica", "Elétrica"),
                    ("Hidraulica", "Hidráulica"),
                    ("Alvenaria", "Alvenaria"),
                    ("Acabamento", "Acabamento"),
                    ("Fundacao", "Fundação"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="categoria_uso_padrao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Geral", "Geral"),
                    ("Eletrica", "Elétrica"),
                    ("Hidraulica", "Hidráulica"),
                    ("Alvenaria", "Alvenaria"),
                    ("Acabamento", "Acabamento"),
                    ("Fundacao", "Fundação"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="UsoMaterial",
        ),
    ]
