# Generated by Django 5.2.3 on 2025-07-20 04:52

from core.models.obra import obra_foto_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_backup_backupsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoobra',
            name='imagem',
            field=models.ImageField(upload_to=obra_foto_path),
        ),
    ]
