# Generated by Django 5.2.3 on 2025-07-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_fotoobra_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="status_orcamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="tipo",
            field=models.CharField(
                choices=[("COMPRA", "Compra"), ("ORCAMENTO", "Orçamento")],
                default="COMPRA",
                max_length=10,
            ),
        ),
    ]
