# Generated by Django 5.0.6 on 2025-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_fotoobra_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('ORCAMENTO', 'Orçamento')], default='COMPRA', max_length=10, verbose_name='Tipo'),
        ),
    ]
