# Generated by Django 5.0.6 on 2025-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250801_0904'),
    ]

    operations = [
    ]
