# Generated by Django 5.2.3 on 2025-08-03 15:17

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_status_orcamento_to_compra"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoDespesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anexo", models.FileField(upload_to=core.models.anexo_despesa_path)),
                ("descricao", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "despesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="core.despesa_extra",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnexoLocacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anexo", models.FileField(upload_to=core.models.anexo_locacao_path)),
                ("descricao", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "locacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="core.locacao_obras_equipes",
                    ),
                ),
            ],
        ),
    ]
