# Generated by Django 5.2.3 on 2025-08-04 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_compra_status_orcamento_compra_tipo'),
        ('core', '0026_anexodespesa_anexolocacao'),
    ]

    operations = [
    ]
