# Generated by Django 5.2.3 on 2025-08-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_anexodespesa_anexolocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada sobre a finalidade e características da equipe', null=True, verbose_name='Descrição da Equipe'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_orcamento',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, null=True, verbose_name='Status do Orçamento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('ORCAMENTO', 'Orçamento')], default='COMPRA', max_length=10, verbose_name='Tipo'),
        ),
    ]
