# Generated by Django 5.2.3 on 2025-08-19 17:00

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_equipe_descricao_alter_compra_status_orcamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='forma_pagamento',
            field=models.CharField(choices=[('AVISTA', 'À Vista'), ('PARCELADO', 'Parcelado')], default='AVISTA', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Entrada'),
        ),
        migrations.CreateModel(
            name='AnexoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.anexo_compra_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho_arquivo', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.compra')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Compra',
                'verbose_name_plural': 'Anexos de Compras',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.obra_arquivo_path)),
                ('nome_original', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(choices=[('FOTO', 'Foto'), ('DOCUMENTO', 'Documento'), ('PLANTA', 'Planta/Projeto'), ('CONTRATO', 'Contrato'), ('LICENCA', 'Licença'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('tamanho_arquivo', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.obra')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo de Obra',
                'verbose_name_plural': 'Arquivos de Obras',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.compra')),
            ],
            options={
                'verbose_name': 'Parcela de Compra',
                'verbose_name_plural': 'Parcelas de Compras',
                'ordering': ['compra', 'numero_parcela'],
                'unique_together': {('compra', 'numero_parcela')},
            },
        ),
    ]
