# Generated by Django 5.2.3 on 2025-08-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_status_orcamento_to_compra'),
        ('core', '0029_compra_forma_pagamento_compra_numero_parcelas_and_more'),
    ]

    operations = [
    ]
