# Generated by Django 5.2.3 on 2025-08-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20250821_0142'),
        ('core', '0030_rename_anexo_field'),
    ]

    operations = [
    ]
