# Generated by Django 5.2.3 on 2025-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_merge_20250821_0142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcompra",
            name="categoria_uso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Geral", "Geral"),
                    ("Eletrica", "Elétrica"),
                    ("Hidraulica", "Hidráulica"),
                    ("Alvenaria", "Alvenaria"),
                    ("Acabamento", "Acabamento"),
                    ("Fundacao", "Fundação"),
                    ("FRETE", "Frete"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="categoria_uso_padrao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Geral", "Geral"),
                    ("Eletrica", "Elétrica"),
                    ("Hidraulica", "Hidráulica"),
                    ("Alvenaria", "Alvenaria"),
                    ("Acabamento", "Acabamento"),
                    ("Fundacao", "Fundação"),
                    ("FRETE", "Frete"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
