# Generated by Django 5.2.3 on 2025-08-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20250827_1258'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE core_compra RENAME COLUMN valor_total_liquido TO valor_total;",
            reverse_sql="ALTER TABLE core_compra RENAME COLUMN valor_total TO valor_total_liquido;"
        ),
    ]
