# Generated by Django 5.0 on 2025-09-02 07:55

from django.db import migrations

def create_frete_material(apps, schema_editor):
    """
    Ensures the 'FRETE' material exists.
    This is idempotent, so it can be run multiple times safely.
    """
    Material = apps.get_model('core', 'Material')
    frete_material, created = Material.objects.get_or_create(
        nome='FRETE',
        defaults={
            'unidade_medida': 'un',
            'categoria_uso_padrao': 'FRETE',
        }
    )

    if created:
        print("Created 'FRETE' material.")
    else:
        # Optional: ensure defaults are correct on existing material
        if frete_material.unidade_medida != 'un' or frete_material.categoria_uso_padrao != 'FRETE':
            frete_material.unidade_medida = 'un'
            frete_material.categoria_uso_padrao = 'FRETE'
            frete_material.save()
            print("Updated existing 'FRETE' material to match defaults.")
        else:
            print("'FRETE' material already exists and is correctly configured.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_itemcompra_categoria_uso_and_more'),
    ]

    operations = [
        migrations.RunPython(create_frete_material),
    ]
