# Generated by Django 5.2.3 on 2025-08-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_revert_valor_total_to_valor_total_liquido'),
    ]

    operations = [
        # Rename auto_backup_enabled to backup_enabled
        migrations.RenameField(
            model_name='backupsettings',
            old_name='auto_backup_enabled',
            new_name='backup_enabled',
        ),
        # Add new fields from backup.py model
        migrations.AddField(
            model_name='backupsettings',
            name='backup_frequency',
            field=models.CharField(
                choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')],
                default='weekly',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='max_backups_to_keep',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='backup_location',
            field=models.CharField(default='/backups/', max_length=500),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Remove old fields that don't exist in new model
        migrations.RemoveField(
            model_name='backupsettings',
            name='retention_days',
        ),
        migrations.RemoveField(
            model_name='backupsettings',
            name='max_backups',
        ),
    ]
