# Generated by Django 5.2.3 on 2025-09-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fix_backup_settings_field'),
    ]

    operations = [
    ]
