# Generated by Django 5.2.3 on 2025-09-11 19:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_anexos3_backuplog_branchmanagement_taskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoobra',
            name='s3_anexo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arquivoobra',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='arquivoobra',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.obra_arquivo_path),
        ),
    ]
