# Generated by Django 5.2.3 on 2025-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_obra_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
