# Generated by Django 5.2.3 on 2025-06-14 17:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_funcionario_locado_to_locacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='tipo_pagamento',
            field=models.CharField(choices=[('diaria', 'Diária'), ('metro', 'Por Metro'), ('empreitada', 'Empreitada')], default='diaria', max_length=20),
        ),
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='valor_pagamento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
