# Generated by Django 5.2.3 on 2025-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_set_existing_locacao_fim_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao_obras_equipes',
            name='data_locacao_fim',
            field=models.DateField(blank=True), # Removed default='1970-01-01'
        ),
    ]
