# Generated by Django 5.2.3 on 2025-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_change_locacao_fim_not_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao_obras_equipes',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
