# Generated by Django 5.2.3 on 2025-06-18 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_refactor_usomaterial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcionario",
            name="salario",
        ),
    ]
