# Generated by Django 5.2.3 on 2025-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_adicionar_categoria_uso_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático')], default='manual', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('backup_time', models.TimeField(default='02:00:00')),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('max_backups', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
                'verbose_name_plural': 'Configurações de Backup',
            },
        ),
    ]
